import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../../../packages/ui/tokens/primitives.css";
import "../styles/tokens.css";
import { Navbar, Footer } from "@nar/ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Navbar
          links={[
            { label: "Industries", href: "/industries" },
            { label: "Markets", href: "/markets" },
            { label: "Experience", href: "/experience" },
            { label: "How We Work", href: "/how-we-work" },
            { label: "Services", href: "/services" },
            { label: "About", href: "/about" },
            { label: "Insights", href: "/insights" },
          ]}
          ctaLabel="Contact"
          ctaHref="/contact"
        />
        {children}
        <Footer
          links={[
            { label: "Contact", href: "/contact" },
            { label: "Insights", href: "/insights" },
            { label: "LinkedIn", href: "https://linkedin.com" },
          ]}
        />
      </body>
    </html>
  );
}
